# Generated by Django 4.2.17 on 2025-01-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ration_card',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ration_card',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='beneficiaries',
            name='beneficiary_otp',
            field=models.CharField(default=None, max_length=6),
        ),
        migrations.AddField(
            model_name='beneficiaries',
            name='beneficiary_password',
            field=models.CharField(default=str, max_length=128),
        ),
        migrations.AddField(
            model_name='ration_card',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='ration_card',
            name='password',
            field=models.CharField(default=str, max_length=10),
        ),
        migrations.AlterField(
            model_name='beneficiaries',
            name='beneficiary_aadhaar',
            field=models.CharField(default=str, max_length=10),
        ),
        migrations.AlterField(
            model_name='beneficiaries',
            name='beneficiary_address',
            field=models.CharField(default=str, max_length=100),
        ),
        migrations.AlterField(
            model_name='beneficiaries',
            name='beneficiary_family',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='beneficiaries',
            name='beneficiary_family_size',
            field=models.IntegerField(default=int),
        ),
        migrations.AlterField(
            model_name='beneficiaries',
            name='beneficiary_pincode',
            field=models.CharField(default=str, max_length=6),
        ),
        migrations.AlterField(
            model_name='beneficiaries',
            name='beneficiary_state',
            field=models.CharField(default=str, max_length=20),
        ),
        migrations.AlterField(
            model_name='ration_card',
            name='ration_card_beneficiary_name',
            field=models.CharField(default=str, max_length=20),
        ),
    ]
