# Generated by Django 4.2.17 on 2025-01-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERapp', '0002_remove_ration_card_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaries',
            name='beneficiary_card_no',
            field=models.CharField(default=str, max_length=15),
        ),
        migrations.AlterField(
            model_name='ration_card',
            name='beneficiary_card_no',
            field=models.CharField(default=str, max_length=15),
        ),
    ]
