# Generated by Django 5.1.4 on 2025-01-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERapp', '0003_alter_beneficiaries_beneficiary_card_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaries',
            name='beneficiary_type',
            field=models.CharField(choices=[('select', 'Select'), ('superuser', 'Superuser'), ('fps', 'Fair Price Shop'), ('user', 'User')], default='select', max_length=20, null=True),
        ),
    ]
